theme: jekyll-theme-minimal
title: Boyang Qiu
description: A biochemist turned data scientist.

navbar-links:
    - GitHub: "https://github.com/BoyangQiu"
    - LinkedIn: "https://www.linkedin.com/in/boyangqiu/"
