theme: jekyll-theme-minimal
title: Boyang Qiu
description: A biochemist turned data scientist.

navbar-links:
  About Me: "aboutme"
  Resources:
    - LinkedIn: "https://www.linkedin.com/in/boyangqiu/"
    - GitHub: "https://github.com/BoyangQiu"
